coding:
  piston:
    base-url: ${PISTON_BASE_URL:http://localhost:2000}
    execute-path: /api/v2/execute
    connect-timeout-milliseconds: 5000
    read-timeout-milliseconds: 30000
    maximum-output-characters: 100000