package career_Navigator_parent.notification.enums;

public enum NotificationType {

    APPLICATION_SUBMITTED,
    APPLICATION_STATUS_CHANGED,

    ASSESSMENT_SCHEDULED,
    ASSESSMENT_UPDATED,
    ASSESSMENT_COMPLETED,

    INTERVIEW_SCHEDULED,
    INTERVIEW_RESCHEDULED,
    INTERVIEW_CONFIRMED,
    INTERVIEW_DECLINED,
    INTERVIEW_CANCELLED,
    INTERVIEW_COMPLETED,

    OFFER_SENT,
    OFFER_VIEWED,
    OFFER_ACCEPTED,
    OFFER_REJECTED,
    OFFER_WITHDRAWN,
    OFFER_EXPIRED,

    JOB_POSTED,
    JOB_UPDATED,
    JOB_CLOSED,

    ACCOUNT_UPDATED,
    SYSTEM
}