package career_Navigator_parent.interviewexperience.enums;

public enum InterviewQuestionCategory {

    DSA,
    JAVA,
    SPRING,
    SPRING_BOOT,
    HIBERNATE,
    JPA,
    MICROSERVICES,
    SQL,
    DBMS,
    OPERATING_SYSTEMS,
    COMPUTER_NETWORKS,
    OOPS,
    SYSTEM_DESIGN,
    LOW_LEVEL_DESIGN,
    HIGH_LEVEL_DESIGN,
    FRONTEND,
    JAVASCRIPT,
    TYPESCRIPT,
    ANGULAR,
    REACT,
    CLOUD,
    AWS,
    DEVOPS,
    DOCKER,
    KUBERNETES,
    TESTING,
    APTITUDE,
    REASONING,
    VERBAL,
    BEHAVIORAL,
    HR,
    MANAGERIAL,
    PROJECT_DISCUSSION,
    RESUME_DISCUSSION,
    OTHER
}